### ISSUE TITLE
Can we move this to the @openlightingproject Org please?

### ISSUE THREAD

**Issue by peternewman** [OpenLightingProject/logos#1]
Now we're on GitHub, it would be good to have this under the @openlightingproject organisation and give you a fork if you're happy with that?

**Comment by DouglasHeriot** [comment]
Yes, this sounds like a good idea. I’ll have a look at doing it now…

**Comment by DouglasHeriot** [comment]
Hmm, I tried, but Github says I need admin access to the organisation to do this. (Maybe give me that, then revoke afterwards?)
I also added you as a contributor to this project, but I’m guessing it won’t let you transfer it either.

**Comment by peternewman** [comment]
I've added you to the OLA team, if you can accept that invite (and turn on 2FA if you're not using it already), then we can sort the admin access.

**Comment by peternewman** [comment]
And adding me as a contributor didn't fix it.

**Comment by peternewman** [comment]
In the interim, can you update the title to point to https://www.openlighting.org/ola/ and https://github.com/OpenLightingProject/ola . Thanks.

**Comment by DouglasHeriot** [comment]
Sorry I forgot to respond sooner – I have updated the URLS, and accepted the invitation to the organisation.

**Comment by peternewman** [comment]
No worries, thanks for doing the updates. You should find you've got an email too...

**Comment by peternewman** [comment]
Thanks for sorting it @DouglasHeriot .
