### ISSUE TITLE
Tidy web fitted logo and Photoshop sources

### ISSUE THREAD

**Issue by peternewman** [OpenLightingProject/logos#7]
See https://github.com/OpenLightingProject/ola/pull/1008

Remove empty pixel from original logo-mini.png
OLA-Logo-Fitted-22px@2x.png has empty pixels too

**Comment by dandaka** [comment]
@peternewman Should I commit here or make a PR from a clone?

**Comment by peternewman** [comment]
I don't believe you've got commit rights @dandaka . We go for PRs even if we do have, so other people can comment.

**Comment by peternewman** [comment]
Closed in https://github.com/OpenLightingProject/logos/pull/8 .
